don/cordova-plugin-ble-central

src/android/BLECentralPlugin.java

Android: use background thread for start scan so we don't block the UI thread.
Android log had warnings about the startScan calls blocking the UI thread
for more than 20ms. This change fixes that by running on a background thread.

Android: don't block UI thread to start scan.

---

examples/sensortag_cc2650/.gitignore
examples/sensortag_cc2650/README.md
examples/sensortag_cc2650/config.xml
examples/sensortag_cc2650/hooks/README.md
examples/sensortag_cc2650/www/css/index.css
examples/sensortag_cc2650/www/index.html
examples/sensortag_cc2650/www/js/index.js

Added a new example for the CC2650 Sensortag.  I have tested this locally on my hardware, everything appears to work well except for a small connection bug (peripheral null not found when selecting the device).  If you would like hardware to test on, contact me privately and I can send you a copy of this new sensortag.

Added TI CC2650 SensorTag Example

---

README.md
src/android/BLECentralPlugin.java
src/browser/BLECentralPlugin.js
src/ios/BLECentralPlugin.h
src/ios/BLECentralPlugin.m
www/ble.js

Adds support for getting notified of changes to Bluetooth state on the device.

register for callbacks on Bluetooth state change

---

README.md
src/android/BLECentralPlugin.java
src/android/BLECommand.java
src/android/Peripheral.java
src/browser/BLECentralPlugin.js
src/ios/BLECentralPlugin.h
src/ios/BLECentralPlugin.m
src/wp/BLECentralPlugin.cs
www/ble.js

Please find attached the code for a new function to read the RSSI value from an active BLE connection.

Added ability to read RSSI value from an active BLE connection.

---

README.md
src/android/BLECentralPlugin.java
src/browser/BLECentralPlugin.js
src/ios/BLECentralPlugin.h
src/ios/BLECentralPlugin.m
src/wp/BLECentralPlugin.cs
www/ble.js

Please find attached the code for a:
- ability to turn on duplicates when scanning for a BLE device
- new function to specify options during a scan

Report duplicates during scan

---

README.md

Fix the array indices in the quick example of write characteristic

Fix quick example write characteristic

---

www/ble.js

calling "withPromises" gives an api wrapper that returns Promises for the functions which are compatible with a single success or failure callback.

Add withPromises api object to return promises on functions which allow it

---

README.md

Took me hours reading through all the old issues to find an example of how to use 'read'.  Since there was no 'quick example', I created one based on what I have working in my project.

read() quick example - do something with data read

---

README.md

As per #411. Also adds link to iBeacon plugin.

Add admonition about using with beacons

---

src/android/BLECentralPlugin.java

Fix of nullpointer issue discovered

Fix of issue 504

---

src/android/BLECentralPlugin.java

Saw that you merged my last two PRs - thanks. I noticed this when doing a diff between your master and mine; along the same lines as the last two, this ensures we don't end up with dangling Promises.

Added error when starting a scan while another is running

---

src/ios/BLECentralPlugin.m

- Let's the user create the dialog. 
- Fixes issue #580

Remove dialog for isEnabled and startNotification

---

src/android/Peripheral.java

Update disconnect logic. Don’t call connect errorCallback when the app requests the disconnect. Keep the gatt when disconnecting if autoconnect is true.
Fixes #582

Update disconnect logic

---

README.md
src/ios/BLECentralPlugin.h
src/ios/BLECentralPlugin.m
www/ble.js

add connectedPeripheralsWithServices and peripheralsWithIdentifiers
Fixes #596

autoconnect on ios

---

README.md
src/ios/BLECentralPlugin.h
src/ios/BLECentralPlugin.m

Reverts don/cordova-plugin-ble-central#591

Revert "show Bluetooth settings on iOS"

---

.gitignore
src/ios/CBPeripheral+Extensions.m

Fixes issues with non-serializable properties in some received advertising packets on iOS.

iOS Advertisement Patch

---

README.md
src/android/BLECentralPlugin.java
www/ble.js

Added setPin method that allows to set the pin for a device when it's required.

Add setPin method

---

src/android/BLECentralPlugin.java

compile with android API less than 29

---

src/android/BLECentralPlugin.java

Hi I replaced the deprecated Scanning API by the new one using BluetoothLeScanner
Signed-off-by: Wenzel Reichmuth <wenzel.reichmuth@vraktion.com>

implemented new BluetoothLeScanner API

---

src/android/Peripheral.java

Also made logic for `registerNotifyCallback` more readable

Fix hang when BluetoothGatt null or service not found

---

src/ios/BLECentralPlugin.m

This will now signal an error to the start and stop callbacks if the
characteristic state does not match what is needed for the callback.
Theoretically, start and stop callbacks shouldn't exist concurrently, but if they
somehow end up doing so, each will get notified if the notification state isn't as expected.

More explicitly handle edge cases when starting/stopping notifications on iOS #577

---

README.md
src/browser/BLECentralPlugin.js

This is a fork of https://github.com/don/cordova-plugin-ble-central/pull/868 that addresses the comments in that PR. Now works with the heart rate sensor example application as well.

Web Bluetooth API support (address comments)

---

README.md
hooks/after_prepare.js
plugin.xml

Exclude ACCESS_BACKGROUND_LOCATION from plugin.xml to avoid complications with Capacitor #928

---

README.md
plugin.xml
src/android/BLECentralPlugin.java
types.d.ts

Implement forceScanFilter for Android

---

src/ios/BLECentralPlugin.m

Closes #1014, #905, #919, #741

Assorted iOS fixes

---

README.md
src/android/BLECentralPlugin.java
src/android/BLECommand.java
src/android/L2CAPContext.java
src/android/Peripheral.java

Fix broadcast receivers on Android 14 (API 34)
