- www/ble.js
device_id should be used findPeripheralByUUID
https://github.com/don/cordova-plugin-ble-central/blob/master/src/ios/BLECentralPlugin.m#L255
> Fixed: isConnected crash

- src/ios/BLECentralPlugin.m
There is no way to cancel pending connections in iOS. This change cancels active and pending connections to a peripheral.
> Disconnect cancels pending connections on iOS

- src/android/Peripheral.java
if type flag of advertising data of peripheral is not ble flag(0x06), android(SDK<23) will use classic port to connect peripheral, so conection will be fail
add connection port type for android(SDK 23)can connect to no ble type flag peripheral
> Connect to no ble flag peripheral (Android SDK 23)

- examples/sensortag_cc2650/www/js/index.js
Currently the "onAccelerometerData" function considers that the Mag data is on the 3,4,5 indexes.
I propose a small correction to the "onAccelerometerData" function in order to display the magnetometer values correctly by changing the indexes from 3,4,5 to 6,7,8.
> Minor correction index.js for the CC2650 example.

- src/ios/CBPeripheral+Extensions.m
Working on a Cordova application that needs to read individual bytes from a
BLE advertisement, I found that on iOS I would occasionally get an uncaught
NSException in the first for loop in serializableAdvertisementData().
I didn't know any Objective-C, but my colleague Asa Freedman could tell
what the for loop was doing, and that it would succeed when serviceData
had no more than one key, otherwise throwing NSException.
Here's a one-liner fix to enumerate a copy of the keys instead of the
object directly.
Signed-off-by: Lebbeous Fogle-Weekley <lebbeous@gmail.com>
> Avoid iOS exception: separate mutation, enumeration of advertisement dict

- README.md
Many thanks for your fantastic plugin !
I just spent two hours pulling my hair out about why a new Nexus 7 2013 was not finding any BLE devices... will surely save someone else the trouble if this quirk is documented alongside scan/startScan
> include note in scan/startScan about LocationServices

- src/android/BLECentralPlugin.java
For some android 4.3 device
SDK 18 is support ble
but bluetooth hardware not support ble
> check BLE feature for some android 4.3 device

- src/android/BLECentralPlugin.java
- src/android/Peripheral.java
Prior to these changes, the plugin would dismiss Peripherals that were connecting (i.e. not yet connected) when it initiated a scan. This resulted in devices that were connected to the phone, but invisible to any methods in the library.
> Prevents scan from removing connecting Peripherals on Android

- src/ios/BLECentralPlugin.m
If I subscribe for notification to the same characteristic's uuid but of two different services, Android is notified property,  iOS notifies the last recorded callback and not the correct one.
The problem is how the keys are stored in the dictionary (method: ```-(NSString *) keyForPeripheral: (CBPeripheral *)peripheral andCharacteristic:(CBCharacteristic *)characteristic``` )
because the key is composed from peripheral's uuid and characteristic's uuid, adding the service's uuid in the key, the problem is solved.
> Use same characteristic uuid with different service in iOS

- src/ios/BLECentralPlugin.m
We should remove pending stopNotificationCallback when already startNotification requested
> Remove pending stopNotificationCallback

- www/ble.js
A few promisified methods were missing `resolve` and `reject` callbacks. This PR adds them.
> add missing `resolve` and `reject` callbacks

- src/ios/CBPeripheral+Extensions.m
In order to avoid https://github.com/don/cordova-plugin-ble-peripheral/issues/1 it's better to have the C function declared as static
> Fix duplicate symbol when using with with cordova-plugin-ble-peripheral

- src/ios/BLECentralPlugin.m
handle read callback errors just like didWriteValueForCharacteristic to prevent the following exception:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
> handle errors in didUpdateValueForCharacteristic

- src/ios/BLECentralPlugin.h
- src/ios/BLECentralPlugin.m
Was misspelled as discoverPeripherialCallbackId.
> Fixed spelling of discoverPeripheralCallbackId

- plugin.xml
It doesn't change anything in the behavior ot he plugin, but
it allows cordova 6.3.0 to *NOT* download it (as it is already
included in the cordova lib)
> Updated cordova plugin compat version number

- src/ios/BLECentralPlugin.m
- src/ios/CBPeripheral+Extensions.h
- src/ios/CBPeripheral+Extensions.m
iOS now deprecates calling RSSI on a CBPeripheral directly (https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518869-rssi), so I eliminated it in favor of using readRSSI for all cases. I combined the caching of its return value with the advertisement data so the most recent value can always be obtained.
There was also a build warning due to using getBytes without specifying a length (potential buffer overflow). I added the requisite length specifier, and also made formatting consistent throughout BLECentralPlugin.m.
> Fixed deprecated iOS CBPeripheral RSSI calls and build warning

- src/ios/BLECentralPlugin.m
Issuing some commands from JS when a peripheral was disconnected would cause API misuse warnings to print to the console on iOS. I trapped these in the plugin code so that the error does not reach the OS but instead propagates back to JS properly, allowing the JS developer to fix their logic.
> Trapped commands that caused iOS API misuse warnings

- src/ios/BLECentralPlugin.h
- src/ios/BLECentralPlugin.m
When a device was disconnecting, callbacks would sometimes not fire (similar effect to the problem fixed by #447). Since iOS uses several callback dictionaries, I added a function that fires failure on all of them, to be called when a disconnect occurs.
> Fixed failure to fire callbacks on iOS when device is disconnecting

- src/android/Peripheral.java
Right now when you try to write or read to a non-existing service, the plugin crashes.
I think it should return gracefully an error, like we are doing with characteristics.
> Explicit handling when trying to write to a non-existing service

- src/ios/BLECentralPlugin.m
It was possible to cause an NSInvalidArgumentException by passing 'undefined' as an argument. Using [command argumentAtIndex] instead of [command.arguments objectAtIndex], the nil is properly passed on, so the JS developer can hopefully trace the bad argument faster.
> Fixed NSInvalidArgumentException when 'undefined' passed to plugin cmds

- src/android/Peripheral.java
This is a minimized version of the fix I previously put in #447, which should also be compatible with auto-connect.
> Fixed failure to fire callbacks on Android when read or write in flight

- src/android/Peripheral.java
Since gattConnect() and JS-initiated disconnects both flush the operations queue, they should fire callbacks on any queued operations. I also realized there was a potential for a data race if a callback arrives from Android at the same time as a disconnect, so I placed the GATT disconnect call before the flush - hopefully no callbacks can come after `gatt.disconnect()`. In case I'm wrong, though, I added intrinsic locks around the accesses to `readCallback` and `writeCallback`, which should prevent any nastiness.
> Fixed dangling promises when reconnecting

- README.md
- src/ios/BLECentralPlugin.h
- src/ios/BLECentralPlugin.m
Borrowed code from https://github.com/guyromb/cordova-open-native-settings
If apps start getting rejected by Apple, this will need to be removed.
> show Bluetooth settings on iOS

- README.md
- src/android/BLECentralPlugin.java
- src/android/Peripheral.java
- www/ble.js
#587 
It's a (rudimentary) implementation to clear the cache to fix the outdated services / characteristic issue.
This is for advanced users only. You have to know what you do and what this do.
Usage example: 
Call this `refreshDeviceCache` if connected and wait a few seconds (this method has no complete-callback. The success callback is always called directly after invoke). Then re-connect your device by disconnect and connect again.
> Refresh Device Cache

- src/ios/BLECentralPlugin.m
- Remove the notification callback for only the disconnected peripheral instead of removing all of the peripherals.
Issue: When connecting to two or more peripherals on an iOS device, whenever a peripheral was disconnected, intentionally or not, cleanupOperationCallbacks() removed the specific peripheral from each of the callback dictionaries. However, in the notificationCallbacks dictionary, it was clearing all the objects, removing the other peripherals that still expected to be notifying. If the device connected to the peripherals using autoConnect(), only that peripheral that reconnected would be able to continue firing the callbacks, as the others were removed.
Fix: Remove the specified peripheral, that either disconnected or called stopNotifications(), from the …
> Update to only remove the disconnected peripheral from notificationCallbacks

- README.md
- plugin.xml
nsbluetoothperipheralusagedescription is deprecated in Ios 13+
We should add NSBluetoothAlwaysUsageDescription in the plugin.xml with old $BLUETOOTH_USAGE_DESCRIPTION variable.
> add NSBluetoothAlwaysUsageDescription for IOS13+

- README.md
- src/android/BLECentralPlugin.java
- www/ble.js
This is my solution to #607; it replaces the failure that occurs when location services are disabled with a console warning, and adds an API function isLocationEnabled(). I reasoned that since some devices (such as my Kindle Fire 5th gen and @airbly's Samsung) will successfully scan for devices even with location services off, the failure can't be the correct response. However, an app still needs to have a way to tell if its empty scan results could be because of disabled location services.
> Location services warning

- src/android/BLECentralPlugin.java
- src/android/Peripheral.java
- src/android/UUIDHelper.java
Hello,
this PR contains small improvements
1. We use the printf functionality of the cordova LOG. This helps to reduce the number of created objects when the log level is warn or error. In this case all the created debug strings like "x:" + x won't be created. 
2. Reuse regex pattern. No need to create it for every call.
Sincerely
Christian
> Use printf of cordova for LOG, reuse pattern, improve loop

- README.md
- src/android/BLECentralPlugin.java
- src/android/Peripheral.java
Calls success callback with actual MTU size after a successful MTU size
request.
Calls error callback when an MTU size request fails.
As discussed in #606
> Give the user feedback after an MTU size request

- plugin.xml
- src/android/BLECentralPlugin.java
Since Android API Level 29 (Android 10) Bluetooth discovery now needs permissions for fine location as per [update notes](https://developer.android.com/about/versions/10/privacy/changes#location-telephony-bluetooth-wifi).
This change conditionally checks and requests for both fine and background location (apps with fine location are granted background location [on Android 10](https://developer.android.com/about/versions/10/privacy/changes#access_granted_automatically_when_targeting_android_9_or_lower)) when running on API level 29 onwards.
I've made a pre-release tagged as [1.2.5-android-10](https://github.com/tiagoblackcode/cordova-plugin-ble-central/releases/tag/1.2.5-android-10) to test the change. I've only tested on Ionic Capacitor and seems to work correctly on Android 8 and 10. …
> Request permission for fine and background location on Android

- README.md
- hooks/after_prepare.js
- plugin.xml
- src/android/BLECentralPlugin.java
Hello @don,
I have created a pull request (as discussed in #821) where the ACCESS_BACKGROUND_LOCATION permission is optional.
You can enable it as shown below:
```
$ cordova plugin add cordova-plugin-ble-central --variable ACCESS_BACKGROUND_LOCATION=true
```
- I used a hook of type `after_prepare` to add the `ACCESS_BACKGROUND_LOCATION` on the `AndroidManifest.xml` file. 
- I also used the variable as a preference to use it in the Java file to request the `ACCESS_BACKGROUND_LOCATION` permission dynamically.
- I updated the README.md file with the information about this variable
I tested it and it is working as it should.
> Make ACCESS_BACKGROUND_LOCATION permission optional

- README.md
- src/android/BLECentralPlugin.java
Add Android-only options for `scanMode`, `callbackType`, `matchMode`, `numOfMatches`, `phy`, `legacy`, `reportDelay` for fine-tune of scanning on Android.
Add info into README.
> startScanWithOptions(): Add scanning options for Android BLEScanner.

- src/android/Peripheral.java
Saw a very rare edge case where if multiple reads arrived at the perfect moment they
could run two simultaneous reads at the same time, causing one of the reads
to get the very wrong callback.
In the logs, this looked something like (note two Read logs with no Processing Complete log to separate them):
```
D/BLEPlugin: action = read
D/Peripheral: Queuing Command com.megster.cordova.ble.central.BLECommand@3f5ebef
D/Peripheral: onCharacteristicRead android.bluetooth.BluetoothGattCharacteristic@77276fc
D/Peripheral: Processing Complete
D/Peripheral: Processing Commands
D/BLEPlugin: action = read
D/Peripheral: Queuing Command com.megster.cordova.ble.central.BLECommand@ee5a185
D/Peripheral: Processing Commands
D/Peripheral: Read 84a98001-24c5-4726-9860-0847bb1d01e7
D/Peripheral: Read …
```
> Ensure only a single processCommands loop can run at a time (Android)

- src/ios/BLECentralPlugin.m
Connect & scan especially are problematic if they don't succeed and report
no error.
> Prevent API Misuse warnings on iOS - raise errors instead #828

- README.md
- plugin.xml
- src/ios/BLECentralPlugin.h
- src/ios/BLECentralPlugin.m
- src/ios/CBPeripheral+Extensions.m
- types.d.ts
- www/ble.js
Feature can be activated by setting BLUETOOTH_RESTORE_STATE to true.
iOS connect now also checks for previously discovered peripheral. When used in conjunction with iOS state restoration, allows a previously-known peripheral to be reconnected to directly without needing another peripheral scan.
This brings the behaviour into alignment with Android.
> Allow iOS state restoration as an opt-in feature #717

- src/android/Peripheral.java
- src/android/SequentialCallbackContext.java
- src/ios/BLECentralPlugin.m
- types.d.ts
- www/ble.js
Addressing #95 , this approach is backwards compatible with existing code, but enables implementations to be confident notification registration has succeeded with the peripheral before continuing with additional commands.
> Add withPromises.startNotification that resolves only when notification has been registered on peripheral

- README.md
- plugin.xml
- src/android/BLECentralPlugin.java
- src/android/BLECommand.java
- src/android/L2CAPContext.java
- src/android/Peripheral.java
- src/ios/BLECentralPlugin.h
- src/ios/BLECentralPlugin.m
- src/ios/BLEStreamContext.h
- src/ios/BLEStreamContext.m
- types.d.ts
- www/ble.js
Hello @don 
This was something I recently found need of, and thought perhaps it might be of some interest to you. L2CAP (in case you weren't aware already) is basically a duplex stream "connection oriented channel" available in parallel to the normal GAP/GATT layers. This support is needed in order to fully implement support for the Bluetooth Object Transfer Service, for example. I have projects using this to stream large-ish binary files for example.
L2CAP is supported on iOS 11+, and since late last year, Android 10+ supports this now as well (not in this PR, but is on my todo list for the future PR if you like this one).
Any and all feedback welcome. I've given the interface my best shot, but if you have preferences about it's structure or approach, I'm happy to adjust it to suit. It …
> Implement L2CAP support (iOS & Android)

- src/ios/BLECentralPlugin.m
When setup of a connection to a peripheral fails on iOS, the error object is rather bulky and doesn't include info on what happened. For example, an error might look like:
```
{
id: "632FAD99-9220-6939-5C9D-0D4F0C46DE2C",
rssi: -50,
advertising: {
kCBAdvDataLocalName: "LCM3-00015",
kCBAdvDataIsConnectable: 1,
kCBAdvDataServiceUUIDs: [Object],
},
name: "LCM3-00015",
}
```
`didDisconnectPeripheral` presently strips out `rssi`, `advertising`, and `services`, and adds `errorDescription` to indicate what went wrong. This PR makes `didFailToConnectPeripheral` do the same.
> Make connect failure errors on iOS more concise

- src/android/BLECentralPlugin.java
Possible fix for an issue https://github.com/don/cordova-plugin-ble-central/issues/940
Calling a window.ble.enable method throws an exception.
The exception:
`java.lang.SecurityException: Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } from ProcessRecord{83ef7f3 12239:org.[my appname]/u0a337} (pid=12239, uid=10337) requires android.permission.BLUETOOTH_CONNECT`
Calling new android 12 scan and connect permissions in a bulk fixes the issue.
> fix: android 12 enable permissions call

- README.md
- src/android/BLECentralPlugin.java
- src/android/Peripheral.java
- src/browser/BLECentralPlugin.js
- types.d.ts
- www/ble.js
Tested with Android 10 & Android 11... so far so good 😃
> Implement createBond/getBondState on Android (#605)

- README.md
I've created a module to unify disparities between android and ios advertising payloads, and parse raw android advertising data based on the Bluetooth GAP specification so it can match the pre-parsed ios data.
@don if this module looks good to you, I'd like to refer people to it in the main README so they can skip a lot of the boilerplate that comes along with raw android advertisements.
> Add new module ble-central-advertisements

- README.md
- src/android/BLECentralPlugin.java
- src/browser/BLECentralPlugin.js
- src/ios/BLECentralPlugin.h
- src/ios/BLECentralPlugin.m
- types.d.ts
- www/ble.js
This allows different scan modes to be easily selected while still allowing the scan to be time-limited
> Add duration flag (in seconds) to scan with options

- .github/workflows/capacitor.yaml
- .prettierrc
- plugin.xml
> Android: Add androidx.annotation reference for RequiresPermission attribute

- README.md
- src/android/BLECentralPlugin.java
- src/android/Peripheral.java
Adds android functionality for `connectable`.
Closes https://github.com/don/cordova-plugin-ble-central/issues/823
> Feature Request: isConnectable Property for Android #823

- types.d.ts
In the requestMtu success callback the applied mtu is passed as a parameter. However this parameter is missing in the types.d.ts
> fix: added mtu to success callback

- README.md
- types.d.ts
- www/ble.js
Related to discussion on #1015
> Clarify isConnected usage to clearly demonstrate bool return case

- src/android/BLECentralPlugin.java
A clear exception has been carved out for system broadcasts registered via Context#registerReceiver
See https://developer.android.com/about/versions/14/behavior-changes-14#system-broadcasts
> Only mark export/non-export for non-system receivers on Android v34 (#1020)

- www/ble.js
This changes the plugin so instead of calling cordova directly, it requires cordova/exec and uses it for calling.
This also mimics how its done in plugins from the core cordova team.
fixes #1029
> Update ble.js to use require format

- src/ios/BLECentralPlugin.m
Additional UUID validation on iOS inadvertantly prevented 16 & 32-bit UUID formats from being accepted.
> Fix support for 16 & 32-bit UUIDs on iOS (#1031)
